# Generated by Django 4.2.7 on 2026-02-08 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('summary_json', models.JSONField(default=dict, help_text='Summary statistics in JSON format')),
            ],
            options={
                'verbose_name': 'Equipment Dataset',
                'verbose_name_plural': 'Equipment Datasets',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('flowrate', models.FloatField(help_text='Flowrate in L/min')),
                ('pressure', models.FloatField(help_text='Pressure in bar')),
                ('temperature', models.FloatField(help_text='Temperature in °C')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(help_text='The dataset this equipment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='equipment_api.equipmentdataset')),
            ],
            options={
                'verbose_name': 'Equipment Item',
                'verbose_name_plural': 'Equipment Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset', 'equipment_name'], name='equipment_a_dataset_bcc379_idx')],
            },
        ),
    ]
